<a href="https://colab.research.google.com/github/tr33yut/-Netflix-/blob/main/Project_5001_Clean_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

input_path = r"filtered_box_office_movies 2.csv"
df = pd.read_csv(input_path)

print(f"จำนวนแถวก่อนรวมข้อมูล: {len(df)} แถว")

numeric_cols = ['weekly_hours_viewed', 'weekly_views', 'weekly_rank', 'cumulative_weeks_in_top_10']
for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', '').str.strip(), errors='coerce')

# 3. กำหนดเงื่อนไขการรวมข้อมูล (Aggregation Rules)
agg_rules = {
    'category': 'first',
    'weekly_rank': 'min',                         # อันดับที่ดีที่สุด (เช่น เคยได้ที่ 1)
    'weekly_hours_viewed': 'sum',                 # รวมชั่วโมงรับชมทั้งหมดทุกสัปดาห์
    'weekly_views': 'sum',                        # รวมยอดวิวทั้งหมดทุกสัปดาห์
    'cumulative_weeks_in_top_10': 'max',          # จำนวนสัปดาห์สูงสุดที่ติด Top 10
    'runtime': 'first',
    'Budget_USD': 'first',
    'Box_Office_USD': 'first'
}

agg_rules = {k: v for k, v in agg_rules.items() if k in df.columns}

df_unique = df.groupby('show_title', as_index=False).agg(agg_rules)

df_unique.rename(columns={
    'weekly_rank': 'best_rank',
    'weekly_hours_viewed': 'total_hours_viewed',
    'weekly_views': 'total_views',
    'cumulative_weeks_in_top_10': 'total_weeks_in_top10'
}, inplace=True)

output_path = r"movies_aggregated_unique 3.csv"
df_unique.to_csv(output_path, index=False)

print(f"รวมข้อมูลเสร็จสิ้น เหลือหนังที่ไม่ซ้ำกัน: {len(df_unique)} เรื่อง")
print(f"บันทึกไฟล์ไว้ที่: {output_path}")
df_unique.head(5)

จำนวนแถวก่อนรวมข้อมูล: 2130 แถว
รวมข้อมูลเสร็จสิ้น เหลือหนังที่ไม่ซ้ำกัน: 883 เรื่อง
บันทึกไฟล์ไว้ที่: movies_aggregated_unique 3.csv

,show_title,category,best_rank,total_hours_viewed,total_views,total_weeks_in_top10,runtime,Budget_USD,Box_Office_USD
0,'83,Films (Non-English),4,13650000,8.531250e+04,2,160.0000,36786988,25452983
1,100 Meters,Films (Non-English),6,4600000,2.600000e+06,2,1.7833,No Data / Netflix Original,3611916
2,12 Strong,Films (English),6,16420000,1.263077e+05,2,130.0000,35000000,67450815
3,13 Hours: The Secret Soldiers of Benghazi,Films (English),3,47950000,9.182292e+06,4,2.4000,50000000,69411370
4,1917,Films (English),7,10840000,9.109244e+04,1,119.0000,100000000,446064352

In [ ]:
import pandas as pd
import requests

input_path = r"movies_with_imdb_id_final 4.csv"
output_path = r"movies_with_ratings_complete 5.csv"

print("กำลังอ่านไฟล์ตั้งต้น...")
df = pd.read_csv(input_path, encoding='utf-8-sig')

ratings_url = "https://datasets.imdbws.com/title.ratings.tsv.gz"
local_gz_path = r"D:\5001\Project\title.ratings.tsv.gz"

print("กำลังดาวน์โหลดชุดข้อมูลคะแนนอย่างเป็นทางการจาก IMDb...")
res = requests.get(ratings_url, stream=True, timeout=30)
with open(local_gz_path, "wb") as f:
    for chunk in res.iter_content(chunk_size=1024 * 1024):
        if chunk:
            f.write(chunk)

print("ดาวน์โหลดสำเร็จ! กำลังรวมคะแนนเข้ากับรายชื่อหนัง...")

ratings_df = pd.read_csv(local_gz_path, sep='\t', compression='gzip')

merged_df = pd.merge(
    df,
    ratings_df[['tconst', 'averageRating', 'numVotes']],
    left_on='imdb_id',
    right_on='tconst',
    how='left'
)

merged_df = merged_df.rename(columns={
    'averageRating': 'imdb_rating',
    'numVotes': 'imdb_total_votes'
}).drop(columns=['tconst'])

merged_df.to_csv(output_path, index=False, encoding='utf-8-sig')

success_count = merged_df['imdb_rating'].notna().sum()
print(f"\n รวมข้อมูลคะแนนสำเร็จเรียบร้อย!")
print(f"- พบข้อมูลคะแนน: {success_count} จากทั้งหมด {len(merged_df)} เรื่อง")
print(f"- บันทึกไฟล์ไว้ที่: {output_path}")

merged_df[['show_title', 'Box_Office_USD', 'imdb_rating', 'imdb_total_votes']].head(5)

กำลังอ่านไฟล์ตั้งต้น...
กำลังดาวน์โหลดชุดข้อมูลคะแนนอย่างเป็นทางการจาก IMDb...
ดาวน์โหลดสำเร็จ! กำลังรวมคะแนนเข้ากับรายชื่อหนัง...

 รวมข้อมูลคะแนนสำเร็จเรียบร้อย!
- พบข้อมูลคะแนน: 868 จากทั้งหมด 881 เรื่อง
- บันทึกไฟล์ไว้ที่: movies_with_ratings_complete 5.csv

,show_title,Box_Office_USD,imdb_rating,imdb_total_votes
0,'83,25452983,7.5,43430.0
1,100 Meters,3611916,7.6,8869.0
2,12 Strong,67450815,6.6,102075.0
3,13 Hours: The Secret Soldiers of Benghazi,69411370,7.3,182498.0
4,1917,446064352,8.2,786332.0

In [ ]:
import pandas as pd
import requests
import re
import time

# 1. โหลดไฟล์ข้อมูลที่คลีนแล้ว (881 เรื่อง)
input_path = r"movies_aggregated_unique 3.csv"
output_path = r"movies_with_imdb_id_final 4.csv"

print(" กำลังโหลดไฟล์ข้อมูล...")
df = pd.read_csv(input_path, encoding='utf-8')
print(f"โหลดข้อมูลสำเร็จ ทั้งหมด {len(df)} เรื่อง\n")

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

def fetch_imdb_id(title):
    """ค้นหา IMDb ID โดยรองรับทั้ง slug และ direct query"""
    clean_title = re.sub(r"^[^a-zA-Z0-9]+", "", str(title))
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", clean_title).lower().strip('_')
    first_char = slug[0] if slug else 'a'

    # ยิง 2 รูปแบบ URL เพื่อให้ครอบคลุมชื่อหนังทุกประเภท
    target_urls = [
        f"https://v2.sg.media-imdb.com/suggestion/{first_char}/{slug}.json",
        f"https://v2.sg.media-imdb.com/suggestion/t/{requests.utils.quote(str(title))}.json"
    ]

    for url in target_urls:
        try:
            res = requests.get(url, headers=headers, timeout=6)
            if res.status_code == 200:
                data = res.json()
                for item in data.get('d', []):
                    # กรองเฉพาะรหัสที่เป็นภาพยนตร์/ซีรีส์ (ขึ้นต้นด้วย tt)
                    if item.get('id', '').startswith('tt'):
                        return item['id']
        except Exception:
            continue
    return None

# 2. เริ่มลูปดึงรหัส IMDb ID
imdb_ids = []
total = len(df)
print(f"🚀 เริ่มต้นการดึง IMDb ID ทั้งหมด {total} เรื่อง (ใช้เวลาประมาณ 5-6 นาที)...\n")

for i, title in enumerate(df['show_title'], start=1):
    movie_id = fetch_imdb_id(title)
    imdb_ids.append(movie_id)

    status = f" พบ ID: {movie_id}" if movie_id else "❌ ไม่พบ ID"
    print(f"[{i}/{total}] {title} -> {status}")

    # หน่วงเวลา 0.35 วินาที เพื่อความปลอดภัยไม่ให้โดนบล็อก
    time.sleep(0.35)

    # เซฟสำรองข้อมูลทุกๆ 50 เรื่อง ป้องกันกรณีเน็ตหลุดระหว่างทาง
    if i % 50 == 0:
        df_temp = df.iloc[:i].copy()
        df_temp['imdb_id'] = imdb_ids
        df_temp.to_csv(output_path, index=False, encoding='utf-8-sig')
        print(f"--- บันทึกข้อมูลสำรองชั่วคราวแล้ว ({i}/{total} เรื่อง) ---\n")

# 3. บันทึกผลลัพธ์ไฟล์สมบูรณ์
df['imdb_id'] = imdb_ids
df.to_csv(output_path, index=False, encoding='utf-8-sig')

found_count = df['imdb_id'].notna().sum()
print(f"\n ดึงข้อมูลเสร็จสิ้น!")
print(f"- สำเร็จ: {found_count}/{total} เรื่อง")
print(f"- บันทึกไฟล์ไว้ที่: {output_path}")
df[['show_title', 'best_rank', 'Box_Office_USD', 'imdb_id']].head(10)

 กำลังโหลดไฟล์ข้อมูล...
โหลดข้อมูลสำเร็จ ทั้งหมด 883 เรื่อง

🚀 เริ่มต้นการดึง IMDb ID ทั้งหมด 883 เรื่อง (ใช้เวลาประมาณ 5-6 นาที)...

[1/883] '83 ->  พบ ID: tt7518786
[2/883] 100 Meters ->  พบ ID: tt32600395
[3/883] 12 Strong ->  พบ ID: tt1413492
[4/883] 13 Hours: The Secret Soldiers of Benghazi ->  พบ ID: tt4172430
[5/883] 1917 ->  พบ ID: tt8579674
[6/883] 2 Guns ->  พบ ID: tt1272878
[7/883] 21 Jump Street ->  พบ ID: tt1232829
[8/883] 211 ->  พบ ID: tt4976192
[9/883] 27 Dresses ->  พบ ID: tt0988595
[10/883] 28 Weeks Later ->  พบ ID: tt0463854
[11/883] 28 Years Later ->  พบ ID: tt10548174
[12/883] 365 Days ->  พบ ID: tt10886166
[13/883] 4 Kings 2 ->  พบ ID: tt30195433
[14/883] 40 Acres ->  พบ ID: tt29634843
[15/883] 47 Meters Down: Uncaged ->  พบ ID: tt7329656
[16/883] 47 Ronin ->  พบ ID: tt1335975
[17/883] 65 ->  พบ ID: tt12261776
[18/883] A Bad Moms Christmas ->  พบ ID: tt6359956
[19/883] A Boy Called Christmas ->  พบ ID: tt10187208
[20/883] A Brother and 7 Siblings ->  พบ ID: tt32881480
[21/883] A Day to Die ->  พบ ID: tt1606378
[22/883] A Dog's Journey ->  พบ ID: tt8385474
[23/883] A Dog's Way Home ->  พบ ID: tt7616798
[24/883] A HOUSE OF DYNAMITE ->  พบ ID: tt32376165
[25/883] A Hard Day ->  พบ ID: tt3697626
[26/883] A Journey ->  พบ ID: tt8385474
[27/883] A Man Called Otto ->  พบ ID: tt7405458
[28/883] A Perfect Getaway ->  พบ ID: tt0971209
[29/883] A Quiet Place Part II ->  พบ ID: tt8332922
[30/883] A Quiet Place: Day One ->  พบ ID: tt13433802
[31/883] A Simple Favor ->  พบ ID: tt7040874
[32/883] A Time to Kill ->  พบ ID: tt0117913
[33/883] A Very Good Girl ->  พบ ID: tt27327494
[34/883] A Walk Among the Tombstones ->  พบ ID: tt0365907
[35/883] Abduction ->  พบ ID: tt1600195
[36/883] Abominable ->  พบ ID: tt6324278
[37/883] About My Father ->  พบ ID: tt8373206
[38/883] Adipurush ->  พบ ID: tt12915716
[39/883] After Ever Happy ->  พบ ID: tt13070038
[40/883] After We Fell ->  พบ ID: tt13069986
[41/883] Agak Laen: Menyala Pantiku! ->  พบ ID: tt32351597
[42/883] Air Force The Movie: Danger Close ->  พบ ID: tt14571464
[43/883] Alas Roban ->  พบ ID: tt39018552
[44/883] Alita: Battle Angel ->  พบ ID: tt0437086
[45/883] All My Life ->  พบ ID: tt8305852
[46/883] All Quiet on the Western Front ->  พบ ID: tt1016150
[47/883] Aloha ->  พบ ID: tt1243974
[48/883] Along Came a Spider ->  พบ ID: tt0164334
[49/883] Alpha ->  พบ ID: tt28363783
[50/883] Alvin and the Chipmunks: Chipwrecked ->  พบ ID: tt1615918
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (50/883 เรื่อง) ---

[51/883] Alvin and the Chipmunks: The Squeakquel ->  พบ ID: tt1231580
[52/883] Amaran ->  พบ ID: tt27118357
[53/883] Amazon Bullseye ->  พบ ID: tt33364791
[54/883] Ambulance ->  พบ ID: tt4998632
[55/883] American Assassin ->  พบ ID: tt1961175
[56/883] American Made ->  พบ ID: tt3532216
[57/883] American Sniper ->  พบ ID: tt2179136
[58/883] Amores perros ->  พบ ID: tt0245712
[59/883] Anaconda ->  พบ ID: tt33244668
[60/883] And The Breadwinner Is... ->  พบ ID: tt34459219
[61/883] Animal ->  พบ ID: tt5574490
[62/883] Anna ->  พบ ID: tt36937503
[63/883] Anyone But You ->  พบ ID: tt26047818
[64/883] Aquaman ->  พบ ID: tt1477834
[65/883] Aquaman and the Lost Kingdom ->  พบ ID: tt9663764
[66/883] Army of Thieves ->  พบ ID: tt13024674
[67/883] Army of the Dead ->  พบ ID: tt0993840
[68/883] Arthur the King ->  พบ ID: tt10720352
[69/883] Article 370 ->  พบ ID: tt30970235
[70/883] Assassin's Creed ->  พบ ID: tt2094766
[71/883] Astérix & Obélix: The Middle Kingdom ->  พบ ID: tt11210390
[72/883] Atlas ->  พบ ID: tt14856980
[73/883] Azaad ->  พบ ID: tt26439870
[74/883] Baby Driver ->  พบ ID: tt3890160
[75/883] Bad Boys for Life ->  พบ ID: tt1502397
[76/883] Bad Boys: Ride or Die ->  พบ ID: tt4919268
[77/883] Ballerina ->  พบ ID: tt7181546
[78/883] Banduan ->  พบ ID: tt38047685
[79/883] Barbarian ->  พบ ID: tt15791034
[80/883] Battleship ->  พบ ID: tt1440129
[81/883] Baywatch ->  พบ ID: tt1469304
[82/883] Beauty and the Beast ->  พบ ID: tt2771200
[83/883] Bee Movie ->  พบ ID: tt0389790
[84/883] Beetlejuice Beetlejuice ->  พบ ID: tt2049403
[85/883] Ben & Jody ->  พบ ID: tt13393058
[86/883] Ben Is Back ->  พบ ID: tt7545524
[87/883] Best. Christmas. Ever! ->  พบ ID: tt2347285
[88/883] Bhool Bhulaiyaa 2 ->  พบ ID: tt6455162
[89/883] Bhool Bhulaiyaa 3 ->  พบ ID: tt26932223
[90/883] Bhooth Bangla ->  พบ ID: tt29540862
[91/883] Big George Foreman: The Miraculous Story of the Once and Future Heavyweight Champion of the World ->  พบ ID: tt12226632
[92/883] Biker ->  พบ ID: tt31593809
[93/883] Black Adam ->  พบ ID: tt6443346
[94/883] Black and Blue ->  พบ ID: tt7390646
[95/883] Blacklight ->  พบ ID: tt14060094
[96/883] Blade Runner 2049 ->  พบ ID: tt1856101
[97/883] Blended ->  พบ ID: tt1086772
[98/883] Blonde ->  พบ ID: tt1655389
[99/883] Blood & Gold ->  พบ ID: tt18073328
[100/883] Blood Brothers: Fury of the Dragon ->  พบ ID: tt32369229
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (100/883 เรื่อง) ---

[101/883] Bloodshot ->  พบ ID: tt1634106
[102/883] Border 2 ->  พบ ID: tt30387012
[103/883] Boxer ->  พบ ID: tt0118760
[104/883] Breaking In ->  พบ ID: tt7137846
[105/883] Bro ->  พบ ID: tt26675491
[106/883] Brother in Love 2 ->  พบ ID: tt12738164
[107/883] Budapest ->  พบ ID: tt2278388
[108/883] Buen Camino ->  พบ ID: tt38350059
[109/883] Bullet Train ->  พบ ID: tt12593682
[110/883] Burlesque ->  พบ ID: tt1126591
[111/883] CHIPS ->  พบ ID: tt0493405
[112/883] CJ7 ->  พบ ID: tt0940709
[113/883] Can You Keep a Secret? ->  พบ ID: tt8707922
[114/883] Captain Underpants: The First Epic Movie ->  พบ ID: tt2091256
[115/883] Carandiru ->  พบ ID: tt0293007
[116/883] Casper ->  พบ ID: tt0112642
[117/883] Cat & Dog ->  พบ ID: tt18113118
[118/883] Central Intelligence ->  พบ ID: tt1489889
[119/883] Chantal im Märchenland ->  พบ ID: tt27075304
[120/883] Charlie and the Chocolate Factory ->  พบ ID: tt0367594
[121/883] Charlie's Angels ->  พบ ID: tt0160127
[122/883] Chhaava ->  พบ ID: tt27922706
[123/883] Chickenhare and the Hamster of Darkness ->  พบ ID: tt12532368
[124/883] City Hunter ->  พบ ID: tt0103950
[125/883] City of God ->  พบ ID: tt0317248
[126/883] Cleaner ->  พบ ID: tt0896798
[127/883] Coach Carter ->  พบ ID: tt0393162
[128/883] Cocktail 2 ->  พบ ID: tt35064672
[129/883] Code 8 ->  พบ ID: tt6259380
[130/883] Cold Pursuit ->  พบ ID: tt5719748
[131/883] Collateral ->  พบ ID: tt0369339
[132/883] Collision ->  พบ ID: tt38116565
[133/883] Colombiana ->  พบ ID: tt1657507
[134/883] Concrete Utopia ->  พบ ID: tt13086266
[135/883] Conquer: Lahad Datu ->  พบ ID: tt30526240
[136/883] Copshop ->  พบ ID: tt5748448
[137/883] Copycat ->  พบ ID: tt0112722
[138/883] Court: State vs A Nobody ->  พบ ID: tt33307144
[139/883] Crawl ->  พบ ID: tt8364368
[140/883] Creed ->  พบ ID: tt3076658
[141/883] Creed III ->  พบ ID: tt11145118
[142/883] Crew ->  พบ ID: tt38218082
[143/883] Crossroads ->  พบ ID: tt0275022
[144/883] Cuando acecha la maldad ->  พบ ID: tt16300962
[145/883] D.I.S.C.O. ->  พบ ID: tt27352181
[146/883] Daddy Day Care ->  พบ ID: tt0317303
[147/883] Daddy's Home 2 ->  พบ ID: tt5657846
[148/883] Damsel ->  พบ ID: tt13452446
[149/883] Dancing Village : The Curse Begins ->  พบ ID: tt28763074
[150/883] Dangal ->  พบ ID: tt5074352
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (150/883 เรื่อง) ---

[151/883] Dangerous ->  พบ ID: tt32299316
[152/883] Dangerous Liaisons ->  พบ ID: tt0094947
[153/883] David -> ❌ ไม่พบ ID
[154/883] Dead Man Down ->  พบ ID: tt2101341
[155/883] Death Whisperer 2 ->  พบ ID: tt31513578
[156/883] Death on the Nile ->  พบ ID: tt7657566
[157/883] Deep ->  พบ ID: tt29516222
[158/883] Deep Impact ->  พบ ID: tt0120647
[159/883] Demon Slayer: Kimetsu no Yaiba Infinity Castle I ->  พบ ID: tt32820897
[160/883] Den of Thieves ->  พบ ID: tt1259528
[161/883] Den of Thieves 2: Pantera ->  พบ ID: tt8008948
[162/883] Despicable Me ->  พบ ID: tt1323594
[163/883] Despicable Me 2 ->  พบ ID: tt1690953
[164/883] Despicable Me 3 ->  พบ ID: tt3469046
[165/883] Despicable Me 4 ->  พบ ID: tt7510222
[166/883] Deva ->  พบ ID: tt27852049
[167/883] Devara ->  พบ ID: tt11821912
[168/883] Devotion ->  พบ ID: tt7693316
[169/883] Dhamaka ->  พบ ID: tt13510660
[170/883] Dhurandhar ->  พบ ID: tt33014583
[171/883] Dhurandhar The Revenge (Raw & Undekha) ->  พบ ID: tt39139925
[172/883] Dirty Grandpa ->  พบ ID: tt1860213
[173/883] Disturbia ->  พบ ID: tt0486822
[174/883] Dog Man ->  พบ ID: tt10954718
[175/883] Dolittle ->  พบ ID: tt6673612
[176/883] Don't Breathe 2 ->  พบ ID: tt4160708
[177/883] Don't Leave ->  พบ ID: tt0100134
[178/883] Don't Look Up ->  พบ ID: tt22096280
[179/883] Don't Move ->  พบ ID: tt29630464
[180/883] Don't Say a Word ->  พบ ID: tt0260866
[181/883] Dora and the Lost City of Gold ->  พบ ID: tt7547410
[182/883] Double Jeopardy ->  พบ ID: tt0150377
[183/883] Dr. Cheon and the Lost Talisman ->  พบ ID: tt29005755
[184/883] Dr. Seuss' The Lorax ->  พบ ID: tt1482459
[185/883] Dracula Untold ->  พบ ID: tt0829150
[186/883] Dragged Across Concrete ->  พบ ID: tt6491178
[187/883] Dragon ->  พบ ID: tt11198330
[188/883] Dragon Ball Z: Battle of Gods ->  พบ ID: tt2263944
[189/883] Dumb Money ->  พบ ID: tt13957560
[190/883] Dune ->  พบ ID: tt15239678
[191/883] Dungeons & Dragons: Honor Among Thieves ->  พบ ID: tt2906216
[192/883] Dunki ->  พบ ID: tt15428134
[193/883] Dynasty Warriors ->  พบ ID: tt7587604
[194/883] Earwig and the Witch ->  พบ ID: tt12441478
[195/883] Edge of Tomorrow ->  พบ ID: tt1631867
[196/883] El Infierno ->  พบ ID: tt1692190
[197/883] Elektra ->  พบ ID: tt0357277
[198/883] Elite Squad ->  พบ ID: tt0861739
[199/883] Elysium ->  พบ ID: tt1535108
[200/883] Emergency ->  พบ ID: tt0068067
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (200/883 เรื่อง) ---

[201/883] Emily the Criminal ->  พบ ID: tt15255876
[202/883] Enforcement ->  พบ ID: tt11081050
[203/883] Enough ->  พบ ID: tt0278435
[204/883] Escape ->  พบ ID: tt6866266
[205/883] Escape From Mogadishu ->  พบ ID: tt14810692
[206/883] Escape Plan 2: Hades ->  พบ ID: tt6513656
[207/883] Escape Room ->  พบ ID: tt5886046
[208/883] Even If This Love Disappears Tonight ->  พบ ID: tt39049192
[209/883] Exhuma ->  พบ ID: tt27802490
[210/883] Exodus: Gods and Kings ->  พบ ID: tt1528100
[211/883] Extinction ->  พบ ID: tt3467412
[212/883] F9: The Fast Saga ->  พบ ID: tt5433138
[213/883] Failure to Launch ->  พบ ID: tt0427229
[214/883] Faith in the Impossible ->  พบ ID: tt37360331
[215/883] Faithfully Yours ->  พบ ID: tt20119468
[216/883] Fall ->  พบ ID: tt15325794
[217/883] Faraway ->  พบ ID: tt7734244
[218/883] Fast & Furious Presents: Hobbs & Shaw ->  พบ ID: tt6806448
[219/883] Fast X ->  พบ ID: tt5433140
[220/883] Faster ->  พบ ID: tt1433108
[221/883] Father Stu ->  พบ ID: tt14439896
[222/883] Fear Street Part 1: 1994 ->  พบ ID: tt6566576
[223/883] Ferdinand ->  พบ ID: tt3411444
[224/883] Fierce ->  พบ ID: tt0401420
[225/883] Fifty Shades Freed ->  พบ ID: tt4477536
[226/883] Final Score ->  พบ ID: tt5254610
[227/883] Firedrake the Silver Dragon ->  พบ ID: tt7080422
[228/883] Firefighters ->  พบ ID: tt32628369
[229/883] First Kill ->  พบ ID: tt13315156
[230/883] Flight ->  พบ ID: tt0481522
[231/883] Flightplan ->  พบ ID: tt0408790
[232/883] Flu ->  พบ ID: tt17677434
[233/883] Flushed Away ->  พบ ID: tt0424095
[234/883] Focus ->  พบ ID: tt2381941
[235/883] Force of Nature ->  พบ ID: tt20256448
[236/883] Ford v. Ferrari ->  พบ ID: tt1950186
[237/883] Four Brothers ->  พบ ID: tt0430105
[238/883] Frankenstein ->  พบ ID: tt1312221
[239/883] Freelance ->  พบ ID: tt15744298
[240/883] Fullmetal Alchemist The Final Alchemy ->  พบ ID: tt18671660
[241/883] Furiosa: A Mad Max Saga ->  พบ ID: tt12037194
[242/883] Fury ->  พบ ID: tt2713180
[243/883] Gangubai Kathiawadi ->  พบ ID: tt10083340
[244/883] Gemini Man ->  พบ ID: tt1025100
[245/883] Geostorm ->  พบ ID: tt1981128
[246/883] Get Hard ->  พบ ID: tt2561572
[247/883] Get Out ->  พบ ID: tt5052448
[248/883] Ghostbusters: Frozen Empire ->  พบ ID: tt21235248
[249/883] Ghosts of the Abyss ->  พบ ID: tt0297144
[250/883] Gifted ->  พบ ID: tt4481414
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (250/883 เรื่อง) ---

[251/883] Gladiator II ->  พบ ID: tt9218128
[252/883] Glass ->  พบ ID: tt6823368
[253/883] Glass Onion: A Knives Out Mystery ->  พบ ID: tt11564570
[254/883] Goat ->  พบ ID: tt27613895
[255/883] Godzilla Minus One ->  พบ ID: tt23289160
[256/883] Godzilla x Kong: The New Empire ->  พบ ID: tt14539740
[257/883] Going in Style ->  พบ ID: tt2568862
[258/883] Golden Kamuy ->  พบ ID: tt8225204
[259/883] Good Bad Ugly ->  พบ ID: tt0060196
[260/883] Good Will Hunting ->  พบ ID: tt0119217
[261/883] Goodbye ->  พบ ID: tt35766629
[262/883] Goosebumps 2: Haunted Halloween ->  พบ ID: tt5664636
[263/883] Grand Isle ->  พบ ID: tt8380776
[264/883] Grave Torture ->  พบ ID: tt27004148
[265/883] Green Lantern ->  พบ ID: tt1133985
[266/883] Green Snake ->  พบ ID: tt0106559
[267/883] Grown Ups ->  พบ ID: tt1375670
[268/883] Grown Ups 2 ->  พบ ID: tt2191701
[269/883] Grudge ->  พบ ID: tt0391198
[270/883] Guess Who ->  พบ ID: tt0372237
[271/883] Gunpowder Milkshake ->  พบ ID: tt8368408
[272/883] Guntur Kaaram ->  พบ ID: tt14564000
[273/883] HELL DOGS - IN THE HOUSE OF BAMBOO - ->  พบ ID: tt19845414
[274/883] HIT: The First Case ->  พบ ID: tt13130760
[275/883] HIT: The Third Case ->  พบ ID: tt23804696
[276/883] Half Brothers ->  พบ ID: tt10515926
[277/883] Hanna ->  พบ ID: tt6932244
[278/883] Happy Gilmore ->  พบ ID: tt0116483
[279/883] Hard Feelings ->  พบ ID: tt15671028
[280/883] Hard Target 2 ->  พบ ID: tt5241578
[281/883] Harold and the Purple Crayon ->  พบ ID: tt1609486
[282/883] Harry Potter and the Sorcerer's Stone ->  พบ ID: tt0241527
[283/883] Heat ->  พบ ID: tt0113277
[284/883] Hellboy ->  พบ ID: tt0167190
[285/883] Hello, Love, Again ->  พบ ID: tt32401874
[286/883] Hi Nanna ->  พบ ID: tt25433734
[287/883] High Plains Drifter ->  พบ ID: tt0068699
[288/883] Hit Man ->  พบ ID: tt20215968
[289/883] Hitman ->  พบ ID: tt0465494
[290/883] Hitman: Agent 47 ->  พบ ID: tt2679042
[291/883] Holy Night: Demon Hunters ->  พบ ID: tt15766876
[292/883] Home ->  พบ ID: tt0099785
[293/883] Homefront ->  พบ ID: tt2312718
[294/883] Honest Thief ->  พบ ID: tt1838556
[295/883] Hop ->  พบ ID: tt27369017
[296/883] Horizon: An American Saga: Chapter 1 ->  พบ ID: tt17505010
[297/883] Hotel Mumbai ->  พบ ID: tt5461944
[298/883] Hotel Transylvania 2 ->  พบ ID: tt2510894
[299/883] Hotel Transylvania 3: Summer Vacation ->  พบ ID: tt5220122
[300/883] How I Became a Gangster ->  พบ ID: tt10804178
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (300/883 เรื่อง) ---

[301/883] How To Make Millions Before Grandma Dies ->  พบ ID: tt31392609
[302/883] How the Grinch Stole Christmas ->  พบ ID: tt0170016
[303/883] How to Lose a Guy in 10 Days ->  พบ ID: tt0251127
[304/883] How to Train Your Dragon ->  พบ ID: tt26743210
[305/883] How to Train Your Dragon: The Hidden World ->  พบ ID: tt2386490
[306/883] Humint ->  พบ ID: tt32606470
[307/883] Hunger ->  พบ ID: tt1392170
[308/883] Hustle ->  พบ ID: tt8009428
[309/883] Hypnotic ->  พบ ID: tt8080204
[310/883] I Am Legend ->  พบ ID: tt0480249
[311/883] I Am the End of the World ->  พบ ID: tt33306253
[312/883] I Know What You Did Last Summer ->  พบ ID: tt4045450
[313/883] I, the Executioner ->  พบ ID: tt30287778
[314/883] IF ->  พบ ID: tt11152168
[315/883] Ice Age: Collision Course ->  พบ ID: tt3416828
[316/883] Ice Age: Dawn of the Dinosaurs ->  พบ ID: tt1080016
[317/883] Identity Thief ->  พบ ID: tt2024432
[318/883] In Her Shoes ->  พบ ID: tt0388125
[319/883] In Time ->  พบ ID: tt1637688
[320/883] In the Heart of the Sea ->  พบ ID: tt1390411
[321/883] Incantation ->  พบ ID: tt18968540
[322/883] Infinite Storm ->  พบ ID: tt14060232
[323/883] Instant Family ->  พบ ID: tt7401588
[324/883] Invasion ->  พบ ID: tt9737326
[325/883] It ->  พบ ID: tt0472954
[326/883] It Ends With Us ->  พบ ID: tt10655524
[327/883] It Takes Two ->  พบ ID: tt0113442
[328/883] Jaat ->  พบ ID: tt32223398
[329/883] Jack -> ❌ ไม่พบ ID
[330/883] Jack Reacher ->  พบ ID: tt0790724
[331/883] Jack Reacher: Never Go Back ->  พบ ID: tt3393786
[332/883] Jawan: Extended Cut ->  พบ ID: tt15354916
[333/883] Jennifer's Body ->  พบ ID: tt1131734
[334/883] Jersey ->  พบ ID: tt8948790
[335/883] John Wick ->  พบ ID: tt2911666
[336/883] John Wick: Chapter 2 ->  พบ ID: tt4425200
[337/883] John Wick: Chapter 3 - Parabellum ->  พบ ID: tt6146586
[338/883] Johnny -> ❌ ไม่พบ ID
[339/883] Journey 2: The Mysterious Island ->  พบ ID: tt1397514
[340/883] Joy Ride ->  พบ ID: tt0206314
[341/883] Jujutsu Kaisen 0: The Movie ->  พบ ID: tt14331144
[342/883] Jules ->  พบ ID: tt15428940
[343/883] Jumanji: The Next Level ->  พบ ID: tt7975244
[344/883] Jumanji: Welcome to the Jungle ->  พบ ID: tt2283362
[345/883] Jumbo ->  พบ ID: tt27433995
[346/883] Jurassic World ->  พบ ID: tt0369610
[347/883] Jurassic World Rebirth ->  พบ ID: tt31036941
[348/883] Jurassic World: Dominion ->  พบ ID: tt8041270
[349/883] Jurassic World: Fallen Kingdom ->  พบ ID: tt4881806
[350/883] Just Go With It ->  พบ ID: tt1564367
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (350/883 เรื่อง) ---

[351/883] Just Like Heaven ->  พบ ID: tt0425123
[352/883] Justice ->  พบ ID: tt0974015
[353/883] KPop Demon Hunters ->  พบ ID: tt14205554
[354/883] Kalki 2898 AD (Hindi) ->  พบ ID: tt12735488
[355/883] Kandahar ->  พบ ID: tt5761544
[356/883] Karate Kid: Legends ->  พบ ID: tt1674782
[357/883] Kate -> ❌ ไม่พบ ID
[358/883] Kick-Ass 2 ->  พบ ID: tt1650554
[359/883] King Arthur: Legend of the Sword ->  พบ ID: tt1972591
[360/883] Kingdom ->  พบ ID: tt0320661
[361/883] Kingdom 3: The Flame of Destiny ->  พบ ID: tt25406052
[362/883] Kingdom: Return of The Great General ->  พบ ID: tt31457736
[363/883] Kingsman: The Golden Circle ->  พบ ID: tt4649466
[364/883] Kingsman: The Secret Service ->  พบ ID: tt2802144
[365/883] Kiss the Girls ->  พบ ID: tt0119468
[366/883] Kiss, Kiss! ->  พบ ID: tt0373469
[367/883] Kleks Academy ->  พบ ID: tt20857676
[368/883] Knight and Day ->  พบ ID: tt1013743
[369/883] Knives Out ->  พบ ID: tt8946378
[370/883] Kraven the Hunter ->  พบ ID: tt8790086
[371/883] Kung Fu Hustle ->  พบ ID: tt0373074
[372/883] Kung Fu Panda 3 ->  พบ ID: tt2267968
[373/883] Kung Fu Panda 4 ->  พบ ID: tt21692408
[374/883] L'amour ouf ->  พบ ID: tt27490099
[375/883] La Huella del Mal ->  พบ ID: tt33098637
[376/883] Laal Singh Chaddha ->  พบ ID: tt10028196
[377/883] Laapataa Ladies ->  พบ ID: tt21626284
[378/883] Labor Day ->  พบ ID: tt1967545
[379/883] Land of Bad ->  พบ ID: tt19864802
[380/883] Lassie Come Home ->  พบ ID: tt0036098
[381/883] Last Seen Alive ->  พบ ID: tt10242388
[382/883] Last Summer ->  พบ ID: tt14550346
[383/883] Last Vegas ->  พบ ID: tt1204975
[384/883] Law Abiding Citizen ->  พบ ID: tt1197624
[385/883] Leatherface ->  พบ ID: tt2620590
[386/883] Leo (Hindi) ->  พบ ID: tt0228334
[387/883] Les Segpa ->  พบ ID: tt19733052
[388/883] Let Go ->  พบ ID: tt9340860
[389/883] Let Him Go ->  พบ ID: tt9340860
[390/883] Life or Something Like It ->  พบ ID: tt0282687
[391/883] Lifemark ->  พบ ID: tt20864704
[392/883] Line of Duty ->  พบ ID: tt2303687
[393/883] Lohusa ->  พบ ID: tt30149921
[394/883] Lone Survivor ->  พบ ID: tt1091191
[395/883] Lost Paradise ->  พบ ID: tt0454970
[396/883] Love Again ->  พบ ID: tt10276482
[397/883] Lucy ->  พบ ID: tt2872732
[398/883] Lyle, Lyle, Crocodile ->  พบ ID: tt14668630
[399/883] M3GAN ->  พบ ID: tt8760708
[400/883] M3GAN 2.0 ->  พบ ID: tt26342662
--- บันทึกข้อมูลสำรองชั่วคราวแล้ว (400/883 เรื่อง) ---

[401/883] Ma ->  พบ ID: tt28014327
[402/883] Maareesan ->  พบ ID: tt29383191
[403/883] Madagascar ->  พบ ID: tt0351283
[404/883] Madagascar: Escape 2 Africa ->  พบ ID: tt0479952
[405/883] Madame Web ->  พบ ID: tt11057302
[406/883] Mafia Mamma ->  พบ ID: tt13923456
[407/883] Maharaja ->  พบ ID: tt26548265
[408/883] Mahavatar Narsimha ->  พบ ID: tt34365591
[409/883] Main Vaapas Aaunga ->  พบ ID: tt37333137
[410/883] Major Grom: Plague Doctor ->  พบ ID: tt7601480
[411/883] Malbatt: Misi Bakara ->  พบ ID: tt22024396
[412/883] Mallari ->  พบ ID: tt29544868
[413/883] Man on Fire ->  พบ ID: tt27331527
[414/883] Manitou's Canoe ->  พบ ID: tt30972054

,show_title,best_rank,Box_Office_USD,imdb_id
0,'83,4,25452983,tt7518786
1,100 Meters,6,3611916,tt32600395
2,12 Strong,6,67450815,tt1413492
3,13 Hours: The Secret Soldiers of Benghazi,3,69411370,tt4172430
4,1917,7,446064352,tt8579674
5,2 Guns,2,131940411,tt1272878
6,21 Jump Street,6,201585328,tt1232829
7,211,6,1052222,tt4976192
8,27 Dresses,7,160300000,tt0988595
9,28 Weeks Later,6,72304846,tt0463854